%https://nl.mathworks.com/help/rtw/ug/edit_template.html
%%base class for adding some custom stuff to the generated .a2l file
classdef GOcontrollASAP2 < coder.asap2.UserCustomizeBase 
	properties
		XCPport
		XCPaddress
		XCPstationId
		Target
	end
	methods
		function obj = GOcontrollASAP2(XCPport, XCPaddress, XCPstationId, Target)

			obj = obj@coder.asap2.UserCustomizeBase();
			obj.XCPport = XCPport;
			obj.XCPaddress = XCPaddress;
			obj.XCPstationId = XCPstationId;
			obj.Target = Target;
		end

        function hardwareInterface = writeHardwareInterface(obj)
            hardwareInterface = sprintf(['    /begin MOD_PAR "' 'UserDefined' '"\n',...
                '\t\tEPK\t\t\t\t"' obj.XCPstationId '"\n',...
                '\t/end MOD_PAR\n\n',...
				'\t/begin IF_DATA_XCP\n',...
				'\t\t/begin XCP_ON_TCP_IP\n',...
				'\t\t\t0x100\n',...
				'\t\t\t' int2str(obj.XCPport) '\n',...
				'\t\t\t"HOST_NAME" ' obj.Target '\n',...
				'\t\t\t"ADDRESS" ' obj.XCPaddress '\n',...
				'\t\t/end XCP_ON_TCP_IP\n',...
				'\t/end IF_DATA_XCP\n',...
				'\n',...
                '    /begin MOD_COMMON "'  'UserDefined MOD_COMMON' '"\n',...
                '      ' obj.ByteOrder '\n',...
                '    /end MOD_COMMON']);
        end
	end
end