%https://nl.mathworks.com/help/rtw/ug/edit_template.html
%%base class for adding some custom stuff to the generated .a2l file
classdef GOcontrollASAP2 < coder.asap2.UserCustomizeBase 
	properties
		XCPport
		XCPaddress
		XCPstationId
		XCPstationIdAddress
		Target
		Medium
		CanSendId
		CanReceiveId
	end
	methods
		function obj = GOcontrollASAP2(XCPport, XCPaddress, XCPstationId, XCPstationIdAddress, Target, Medium, CanSendId, CanReceiveId)

			obj = obj@coder.asap2.UserCustomizeBase();
			obj.XCPport = XCPport;
			obj.XCPaddress = XCPaddress;
			obj.XCPstationId = XCPstationId;
			obj.XCPstationIdAddress = XCPstationIdAddress;
			obj.Target = Target;
			obj.Medium = Medium;
			obj.CanSendId = CanSendId;
			obj.CanReceiveId = CanReceiveId;
		end

		function hardwareInterface = writeHardwareInterface(obj)
			if (strcmp(obj.Medium, 'CAN'))
				hardwareInterface = sprintf([...
					'    /begin MOD_PAR "' 'MOD PAR Comment Goes Here' '"\n',...
					'      ADDR_EPK\t\t\t' obj.XCPstationIdAddress '\n',...
					'      CPU_TYPE\t\t\t"' obj.Target '"\n',...
					'      ECU\t\t\t\t"' obj.Target '"\n',...
					'      EPK\t\t\t\t"' obj.XCPstationId '"\n',...
					'      SYSTEM_CONSTANT\t"XcpStationID string length"  "' int2str(length(obj.XCPstationId)) '"\n',...
					'      SYSTEM_CONSTANT\t"RAM-FlashOffset"  "0"\n',...
					'    /end MOD_PAR\n\n',...
					'    /begin IF_DATA XCP\n',...
					'      /begin XCP_ON_CAN\n',...
					'        0x100\n',... %?
					'        CAN_ID_BROADCAST 0x0\n',...
					'        CAN_ID_MASTER 0x' dec2hex(obj.CanReceiveId) '\n',...
					'        CAN_ID_SLAVE 0x' dec2hex(obj.CanSendId) '\n',...
					'        BAUDRATE 0x3D090\n',... %get this from the model
					'      /end XCP_ON_CAN\n',...
					'    /end IF_DATA XCP\n',...
					'\n',...
					'    /begin MOD_COMMON "'  'Mod Common Comment Here' '"\n',...
					'      ' obj.ByteOrder '\n',...
					'    /end MOD_COMMON'...
				]);
			else
				hardwareInterface = sprintf([...
					'    /begin MOD_PAR "' 'MOD PAR Comment Goes Here' '"\n',...
					'      ADDR_EPK\t\t\t' obj.XCPstationIdAddress '\n',...
					'      CPU_TYPE\t\t\t"' obj.Target '"\n',...
					'      ECU\t\t\t\t"' obj.Target '"\n',...
					'      EPK\t\t\t\t"' obj.XCPstationId '"\n',...
					'      SYSTEM_CONSTANT\t"XcpStationID string length"  "' int2str(length(obj.XCPstationId)) '"\n',...
					'      SYSTEM_CONSTANT\t"RAM-FlashOffset"  "0"\n',...
					'    /end MOD_PAR\n\n',...
					'    /begin IF_DATA XCP\n',...
					'      /begin XCP_ON_' obj.Medium '_IP\n',...
					'        0x100\n',... %?
					'        ' int2str(obj.XCPport) '\n',...
					'        "HOST_NAME" ' obj.Target '\n',...
					'        "ADDRESS" ' obj.XCPaddress '\n',...
					'      /end XCP_ON_' obj.Medium '_IP\n',...
					'    /end IF_DATA XCP\n',...
					'\n',...
					'    /begin MOD_COMMON "'  'Mod Common Comment Here' '"\n',...
					'      ' obj.ByteOrder '\n',...
					'    /end MOD_COMMON'...
				]);
			end
		end
	end
end